### ISSUE TITLE
GitHub Cog use requests instead of github3

### ISSUE THREAD

**Issue by centipeda** [FreeCodeCampGuam/FCCG-Cogs#10]
Planning to use the `requests` module and various GET/POST/PATCH requests to interact with the GitHub API instead of `github3`. `requests` is more widely tested and direct interaction with the API allows for more flexibility.

**Comment by Chovin** [comment]
please don't use `requests`. use `aiohttp` instead as it is not blocking.
explanation as well as some Red conventions are explained in our [little python tut](https://github.com/FreeCodeCampGuam/FreeCodeCampGuamHelp/tree/master/Python).

we should add a link as well as explain that we should be hanging out in Red's Discord server in or to better understand Red conventions and not fall into pitfalls that previous cog devs have.

put that up on the Wiki? #1

**Comment by centipeda** [comment]
Oops, yes. Completely forgot about `requests` being blocking. Can-do.
