### ISSUE TITLE
[rolecall] Installing Cog would initiate installation of non-existing requirements.

### ISSUE THREAD

**Issue by jasperdanan** [FreeCodeCampGuam/FCCG-Cogs#45]
Might be the problem:
https://github.com/FreeCodeCampGuam/FCCG-Cogs/blob/87731733d0bdf956d93e585c63ca10cc341121b4/rolecall/info.json#L8

**Comment by Chovin** [comment]
that's probably the problem, would you mind putting up a PR removing that empty string?

**Comment by jasperdanan** [comment]
Looks like it was fixed in the latest commit under `roleboard` bracnh:
f9785fd4fb8db19e67c1e500da3f48f65cf0a7cd
