### ISSUE TITLE
I would like to port ffplay to discord.py rewrite and red V3

### ISSUE THREAD

**Issue by Stylite** [FreeCodeCampGuam/FCCG-Cogs#52]

**Comment by Chovin** [comment]
I've invited you to the newly created @FreeCodeCampGuam/v3-team 
We'd love your help porting cogs over to v3.
I ask that you keep your v3 work on `v3-` prefixed branches and merge/PR to `v3` as our v3 master.

**Comment by Chovin** [comment]
shall I close this issue and we can move discussions about ffplay over to PRs n such?

**Comment by Stylite** [comment]
Works for me.
